branch-defaults:
  master:
    environment: hackathonplanner
global:
  application_name: Hackathon-Planner
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: eu-central-1
  profile: eb-cli
  sc: git